# Generated by Django 4.1 on 2022-10-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Sub Título')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('contenido', models.TextField(null=True, verbose_name='Contenido')),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateField(null=True)),
            ],
        ),
    ]
