# Generated by Django 4.1 on 2022-10-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_postarticulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostArticulo',
        ),
    ]
